=== bhagya-sk/xml/xmltrial/StudentType.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT students (student+)>
<!ELEMENT student (name,roll_no,subject,age)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT roll_no (#PCDATA)>
<!ELEMENT subject (subname,marks)>
<!ELEMENT subname (#PCDATA)>
<!ELEMENT marks (#PCDATA)>
<!ELEMENT age (#PCDATA)>

=== bhagya-sk/xml/xmltrial/student.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE students SYSTEM "StudentType.dtd">

<students>
	<student>
		<name>ravi</name>
		<roll_no>1</roll_no>
		<subject>
			<subname>maths</subname>
			<marks>78</marks>
		</subject>
		<age>15</age>
	</student>

	<student>
		<name>raksha</name>
		<roll_no>2</roll_no>
		<subject>
			<subname>maths</subname>
			<marks>55</marks>
		</subject>
		<age>15</age>
	</student>

	<student>
		<name>rashmi</name>
		<roll_no>3</roll_no>
		<subject>
			<subname>maths</subname>
			<marks>40</marks>
		</subject>
		<age>15</age>
	</student>

</students>
